{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop-manager.fullname" . }}-frontend
  labels:
    {{- include "shop-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.frontend.service.port | default 3000 }}
      targetPort: {{ .Values.frontend.service.targetPort | default 3000 }}
      protocol: TCP
      name: http
  selector:
    {{- include "shop-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}