{{- if .Values.keycloak.enabled }}
{{- $themeName := include "shop-manager.keycloak.themeName" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shop-manager.themeConfigMapName" . }}
  labels:
    {{- include "shop-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-theme
data:
  theme.properties: |
{{ .Files.Get "keycloak-theme/shop-manager/login/theme.properties" | indent 4 }}

  template.ftl: |
{{ .Files.Get "keycloak-theme/shop-manager/login/template.ftl" | indent 4 }}

  login.ftl: |
{{ .Files.Get "keycloak-theme/shop-manager/login/login.ftl" | indent 4 }}

  shop-manager.css: |
{{ .Files.Get "keycloak-theme/shop-manager/login/resources/css/shop-manager.css" | indent 4 }}
{{- end }}