{{- if and .Values.keycloak.enabled .Values.keycloak.customTheme.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shop-manager.fullname" . }}-keycloak-theme-sa
  labels:
    {{- include "shop-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-theme-rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "shop-manager.fullname" . }}-keycloak-theme-role
  labels:
    {{- include "shop-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-theme-rbac
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["statefulsets/status"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "shop-manager.fullname" . }}-keycloak-theme-rolebinding
  labels:
    {{- include "shop-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-theme-rbac
subjects:
- kind: ServiceAccount
  name: {{ include "shop-manager.fullname" . }}-keycloak-theme-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "shop-manager.fullname" . }}-keycloak-theme-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}